/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1edd_201122841;

/**
 *
 * @author Any
 */
public class CATALOGO_ZOMBIES extends javax.swing.JFrame {

    /**
     * Creates new form CATALOGO_ZOMBIES
     */
    ListaNodo pila = new ListaNodo();

    public CATALOGO_ZOMBIES() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Nombre3 = new javax.swing.JTextField();
        Nombre2 = new javax.swing.JTextField();
        Nombre1 = new javax.swing.JTextField();
        AceptarCatalogo3 = new javax.swing.JButton();
        Label1 = new javax.swing.JLabel();
        Label2 = new javax.swing.JLabel();
        Label3 = new javax.swing.JLabel();
        CAtaque = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        Defensa1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Ataque1 = new javax.swing.JTextField();
        Defensa2 = new javax.swing.JTextField();
        Ataque2 = new javax.swing.JTextField();
        CAtaque1 = new javax.swing.JComboBox();
        Defensa3 = new javax.swing.JTextField();
        Ataque3 = new javax.swing.JTextField();
        CAtaque2 = new javax.swing.JComboBox();
        AceptarCatalogo1 = new javax.swing.JButton();
        AceptarCatalogo2 = new javax.swing.JButton();
        ListoZ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Catalogo Zombies");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Imagen");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 31, -1, -1));

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jLabel4.setText("Tipo Ataque");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));
        getContentPane().add(Nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 63, -1));
        getContentPane().add(Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 63, -1));
        getContentPane().add(Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 63, -1));

        AceptarCatalogo3.setText("ACEPTAR");
        AceptarCatalogo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarCatalogo3ActionPerformed(evt);
            }
        });
        getContentPane().add(AceptarCatalogo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, -1, 20));

        Label1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/golpeador.png"))); // NOI18N
        Label1.setText("jLabel1");
        getContentPane().add(Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 50, 70));

        Label2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LanzaCocos.jpg"))); // NOI18N
        Label2.setText("jLabel2");
        getContentPane().add(Label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 50, 70));

        Label3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Lanzador.jpg"))); // NOI18N
        Label3.setText("jLabel3");
        getContentPane().add(Label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 50, 70));

        CAtaque.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Disparo", "Ataque" }));
        CAtaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAtaqueActionPerformed(evt);
            }
        });
        getContentPane().add(CAtaque, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        jLabel6.setText("Defensa");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));
        getContentPane().add(Defensa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 70, -1));

        jLabel3.setText("Ataque");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));
        getContentPane().add(Ataque1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 70, -1));
        getContentPane().add(Defensa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 70, -1));
        getContentPane().add(Ataque2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 70, -1));

        CAtaque1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Disparo", "Ataque" }));
        getContentPane().add(CAtaque1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));
        getContentPane().add(Defensa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 70, -1));
        getContentPane().add(Ataque3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 70, -1));

        CAtaque2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Disparo", "Ataque" }));
        getContentPane().add(CAtaque2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        AceptarCatalogo1.setText("ACEPTAR");
        AceptarCatalogo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarCatalogo1ActionPerformed(evt);
            }
        });
        getContentPane().add(AceptarCatalogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));

        AceptarCatalogo2.setText("ACEPTAR");
        AceptarCatalogo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarCatalogo2ActionPerformed(evt);
            }
        });
        getContentPane().add(AceptarCatalogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, -1, -1));

        ListoZ.setText("LISTO");
        ListoZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListoZActionPerformed(evt);
            }
        });
        getContentPane().add(ListoZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 100, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarCatalogo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarCatalogo3ActionPerformed
        // TODO add your handling code here:
   String categoria1 = (String) CAtaque1.getSelectedItem();
        boolean tipo;
        if (categoria1=="Disparo") {
            tipo=true;
        }else{
        tipo=false;
        }
        
        String Nombre, Imagen;
        boolean TipoAtaque;
        int Ataque, Defensa;

        CATALOGO_ZOMBIES catalogo = new CATALOGO_ZOMBIES();

        pila.addInicio(new Nodo(Label3.getText(), Nombre3.getText(), true, Integer.parseInt(Defensa3.getText()), Integer.parseInt(Ataque3.getText())));
        System.out.println("Mostrando datos3");
        pila.Mostrar();

    }//GEN-LAST:event_AceptarCatalogo3ActionPerformed

    private void AceptarCatalogo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarCatalogo1ActionPerformed
        // TODO add your handling code here:
        String categoria1 = (String) CAtaque.getSelectedItem();
        boolean tipo;
        if (categoria1=="Disparo") {
            tipo=true;
        }else{
        tipo=false;
        }
        
        pila.addInicio(new Nodo(Label1.getText(), Nombre1.getText(), tipo, Integer.parseInt(Defensa1.getText()), Integer.parseInt(Ataque1.getText())));
        System.out.println("Mostrando datos1");
        pila.Mostrar();
    }//GEN-LAST:event_AceptarCatalogo1ActionPerformed

    private void AceptarCatalogo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarCatalogo2ActionPerformed
        // TODO add your handling code here:
   String categoria1 = (String) CAtaque2.getSelectedItem();
        boolean tipo;
        if (categoria1=="Disparo") {
            tipo=true;
        }else{
        tipo=false;
        }
        pila.addInicio(new Nodo(Label2.getText(), Nombre2.getText(), tipo, Integer.parseInt(Defensa2.getText()), Integer.parseInt(Ataque2.getText())));
        System.out.println("Mostrando datos2");
        pila.Mostrar();
    }//GEN-LAST:event_AceptarCatalogo2ActionPerformed

    private void ListoZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListoZActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_ListoZActionPerformed

    private void CAtaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAtaqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CAtaqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CATALOGO_ZOMBIES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CATALOGO_ZOMBIES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CATALOGO_ZOMBIES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CATALOGO_ZOMBIES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CATALOGO_ZOMBIES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarCatalogo1;
    private javax.swing.JButton AceptarCatalogo2;
    private javax.swing.JButton AceptarCatalogo3;
    private javax.swing.JTextField Ataque1;
    private javax.swing.JTextField Ataque2;
    private javax.swing.JTextField Ataque3;
    private javax.swing.JComboBox CAtaque;
    private javax.swing.JComboBox CAtaque1;
    private javax.swing.JComboBox CAtaque2;
    private javax.swing.JTextField Defensa1;
    private javax.swing.JTextField Defensa2;
    private javax.swing.JTextField Defensa3;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label3;
    private javax.swing.JButton ListoZ;
    public javax.swing.JTextField Nombre1;
    public javax.swing.JTextField Nombre2;
    public javax.swing.JTextField Nombre3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
