package practica1edd_201122841;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Any
 */
public class CATALOGO_PLANTAS extends javax.swing.JFrame {

    /**
     * Creates new form CATALOGO_PLANTAS
     */
    ListaNodo cola = new ListaNodo();
      public CATALOGO_PLANTAS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Nombre3 = new javax.swing.JTextField();
        Nombre2 = new javax.swing.JTextField();
        Nombre1 = new javax.swing.JTextField();
        AceptarCatalogo = new javax.swing.JButton();
        Label1 = new javax.swing.JLabel();
        Label2 = new javax.swing.JLabel();
        Label3 = new javax.swing.JLabel();
        CAtaque = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        Defensa1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Ataque1 = new javax.swing.JTextField();
        Defensa2 = new javax.swing.JTextField();
        Ataque2 = new javax.swing.JTextField();
        CAtaque1 = new javax.swing.JComboBox();
        Defensa3 = new javax.swing.JTextField();
        Ataque3 = new javax.swing.JTextField();
        CAtaque2 = new javax.swing.JComboBox();
        AceptarCatalogo1 = new javax.swing.JButton();
        AceptarCatalogo2 = new javax.swing.JButton();
        ListoP = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Catalogo Plantas");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Imagen");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Tipo Ataque");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));
        getContentPane().add(Nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 63, -1));
        getContentPane().add(Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 63, -1));
        getContentPane().add(Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 63, -1));

        AceptarCatalogo.setText("ACEPTAR");
        AceptarCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarCatalogoActionPerformed(evt);
            }
        });
        getContentPane().add(AceptarCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, -1, 20));

        Label1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lanzacocos.png"))); // NOI18N
        getContentPane().add(Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, 70));

        Label2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/planta.jpg"))); // NOI18N
        getContentPane().add(Label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 50, 70));

        Label3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/golpeador.png"))); // NOI18N
        getContentPane().add(Label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 50, 70));

        CAtaque.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Disparo", "Ataque" }));
        getContentPane().add(CAtaque, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Defensa");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));
        getContentPane().add(Defensa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 70, -1));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Ataque");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));
        getContentPane().add(Ataque1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 70, -1));
        getContentPane().add(Defensa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 70, -1));
        getContentPane().add(Ataque2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 70, -1));

        CAtaque1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Disparo", "Ataque" }));
        getContentPane().add(CAtaque1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));
        getContentPane().add(Defensa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 70, -1));
        getContentPane().add(Ataque3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 70, -1));

        CAtaque2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Disparo", "Ataque" }));
        getContentPane().add(CAtaque2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        AceptarCatalogo1.setText("ACEPTAR");
        AceptarCatalogo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarCatalogo1ActionPerformed(evt);
            }
        });
        getContentPane().add(AceptarCatalogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, -1, -1));

        AceptarCatalogo2.setText("ACEPTAR");
        AceptarCatalogo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarCatalogo2ActionPerformed(evt);
            }
        });
        getContentPane().add(AceptarCatalogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, -1, -1));

        ListoP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aceptar.png"))); // NOI18N
        ListoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListoPActionPerformed(evt);
            }
        });
        getContentPane().add(ListoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 120, 120));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/blanco.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 250));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FICHATECNICA.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 252, 710, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarCatalogoActionPerformed
        // TODO add your handling code here:
        String categoria3 = (String) CAtaque1.getSelectedItem();
        boolean tipo;
        if (categoria3 == "Disparo") {
            tipo = true;
        } else {
            tipo = false;
        }

        String Nombre, Imagen;
        boolean TipoAtaque;
        int Ataque, Defensa;

        CATALOGO_PLANTAS catalogo = new CATALOGO_PLANTAS();

        cola.addFinal(new Nodo(Label3.getText(), Nombre3.getText(), tipo, Integer.parseInt(Defensa3.getText()), Integer.parseInt(Ataque3.getText())));

        System.out.println("Mostrando datos3");
        cola.Mostrar();


    }//GEN-LAST:event_AceptarCatalogoActionPerformed

    private void AceptarCatalogo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarCatalogo1ActionPerformed
        // TODO add your handling code here:
        String categoria1 = (String) CAtaque.getSelectedItem();
        boolean tipo;
        if (categoria1 == "Disparo") {
            tipo = true;
        } else {
            tipo = false;
        }

        cola.addFinal(new Nodo(Label1.getText(), Nombre1.getText(), tipo, Integer.parseInt(Defensa1.getText()), Integer.parseInt(Ataque1.getText())));
        System.out.println("Mostrando datos1");
        cola.Mostrar();
    }//GEN-LAST:event_AceptarCatalogo1ActionPerformed

    private void AceptarCatalogo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarCatalogo2ActionPerformed
        // TODO add your handling code here:
        String categoria2 = (String) CAtaque2.getSelectedItem();
        boolean tipo;
        if (categoria2 == "Disparo") {
            tipo = true;
        } else {
            tipo = false;
        }

        cola.addFinal(new Nodo(Label2.getText(), Nombre2.getText(), tipo, Integer.parseInt(Defensa2.getText()), Integer.parseInt(Ataque2.getText())));
        System.out.println("Mostrando datos2");
        cola.Mostrar();
    }//GEN-LAST:event_AceptarCatalogo2ActionPerformed

    private void ListoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListoPActionPerformed
        // TODO add your handling code here:
        CATALOGO_ZOMBIES catZ = new CATALOGO_ZOMBIES();
        catZ.show();
        this.dispose();
        ((HiloCatalogo) new HiloCatalogo()).stop();


    }//GEN-LAST:event_ListoPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CATALOGO_PLANTAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CATALOGO_PLANTAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CATALOGO_PLANTAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CATALOGO_PLANTAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CATALOGO_PLANTAS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarCatalogo;
    private javax.swing.JButton AceptarCatalogo1;
    private javax.swing.JButton AceptarCatalogo2;
    private javax.swing.JTextField Ataque1;
    private javax.swing.JTextField Ataque2;
    private javax.swing.JTextField Ataque3;
    private javax.swing.JComboBox CAtaque;
    private javax.swing.JComboBox CAtaque1;
    private javax.swing.JComboBox CAtaque2;
    private javax.swing.JTextField Defensa1;
    private javax.swing.JTextField Defensa2;
    private javax.swing.JTextField Defensa3;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label3;
    private javax.swing.JButton ListoP;
    public javax.swing.JTextField Nombre1;
    public javax.swing.JTextField Nombre2;
    public javax.swing.JTextField Nombre3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
