package practica1edd_201122841;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Any
 */
public class CATALOGO extends javax.swing.JFrame {

    /**
     * Creates new form CATALOGO
     */
    ListaNodo cola = new ListaNodo();
        
    public CATALOGO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Nombre3 = new javax.swing.JTextField();
        Nombre2 = new javax.swing.JTextField();
        Nombre1 = new javax.swing.JTextField();
        AceptarCatalogo = new javax.swing.JButton();
        Label1 = new javax.swing.JLabel();
        Label2 = new javax.swing.JLabel();
        Label3 = new javax.swing.JLabel();
        CAtaque = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        CPersonaje = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        Defensa1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Ataque1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Catalogo");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Imagen");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 31, -1, -1));

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 31, -1, -1));

        jLabel4.setText("Tipo Ataque");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));
        getContentPane().add(Nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 164, 63, -1));
        getContentPane().add(Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 126, 63, -1));
        getContentPane().add(Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 88, 63, -1));

        AceptarCatalogo.setText("ACEPTAR");
        AceptarCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarCatalogoActionPerformed(evt);
            }
        });
        getContentPane().add(AceptarCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        Label1.setText("jLabel5");
        getContentPane().add(Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        Label2.setText("jLabel5");
        getContentPane().add(Label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        Label3.setText("jLabel5");
        getContentPane().add(Label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        CAtaque.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(CAtaque, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        jLabel5.setText("Tipo Personaje");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        CPersonaje.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(CPersonaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        jLabel6.setText("Defensa");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));
        getContentPane().add(Defensa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 70, -1));

        jLabel3.setText("Ataque");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, -1, -1));
        getContentPane().add(Ataque1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarCatalogoActionPerformed
        // TODO add your handling code here:
                   
   String Nombre,Imagen;
   boolean TipoAtaque, TipoPersonaje;
   int Ataque,Defensa;
   
   CATALOGO catalogo =new CATALOGO();
   
   cola.addFinal(new Nodo(Label1.getText(),Nombre1.getText(),true,false,Integer.parseInt(Defensa1.getText()),Integer.parseInt(Ataque1.getText())));
   System.out.println("Mostrando datos");
   cola.Mostrar();
        
        
    }//GEN-LAST:event_AceptarCatalogoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CATALOGO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CATALOGO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CATALOGO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CATALOGO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CATALOGO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarCatalogo;
    private javax.swing.JTextField Ataque1;
    private javax.swing.JComboBox CAtaque;
    private javax.swing.JComboBox CPersonaje;
    private javax.swing.JTextField Defensa1;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label3;
    public javax.swing.JTextField Nombre1;
    public javax.swing.JTextField Nombre2;
    public javax.swing.JTextField Nombre3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
