package practica1edd_201122841;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Any
 */
public class PLANTAS extends javax.swing.JFrame {

    /**
     * Creates new form PLANTAS
     */
    // ListaNodo usuario = new ListaNodo();
    public static String usuplantas;
    public PLANTAS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        otroplanta = new javax.swing.JButton();
        NombrePlanta = new javax.swing.JTextField();
        CantidadPlanta = new javax.swing.JTextField();
        AceptarPlantas = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Plantas");
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cantidad");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        otroplanta.setText("Agregar más campos");
        otroplanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otroplantaActionPerformed(evt);
            }
        });
        getContentPane().add(otroplanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));
        getContentPane().add(NombrePlanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 200, -1));
        getContentPane().add(CantidadPlanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 90, -1));

        AceptarPlantas.setForeground(new java.awt.Color(0, 51, 51));
        AceptarPlantas.setText("FINALIZAR");
        AceptarPlantas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarPlantasActionPerformed(evt);
            }
        });
        getContentPane().add(AceptarPlantas, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 100, -1));

        jButton1.setText("Crear usuario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 130, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/plantas.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void otroplantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otroplantaActionPerformed
        // TODO add your handling code here:
        OTROS_CAMPOSPLANTS campoplanta = new OTROS_CAMPOSPLANTS();
        
        campoplanta.show();
    }//GEN-LAST:event_otroplantaActionPerformed

    private void AceptarPlantasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarPlantasActionPerformed
        // TODOqqqq add your handling code here:

   
        jButton1.setEnabled(true);
        otroplanta.setEnabled(false);
        //escondiendo el boton para ya no usarlo y no crear mas usuarios
        PRINCIPAL.Planta = true;
        ((HiloCatalogo) new HiloCatalogo()).start();
        this.dispose();

    }//GEN-LAST:event_AceptarPlantasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (TABLERO.usuarios.Contador() == 0) {
            TABLERO.usuarios.addInicio(new NodoUsuarios(NombrePlanta.getText(), Integer.parseInt(CantidadPlanta.getText())));
            System.out.println("Mostrando usuario planta");
            TABLERO.usuarios.Mostrar();
        } else if (TABLERO.usuarios.Contador() == 1) {
            TABLERO.usuarios.addInicio(new NodoUsuarios(NombrePlanta.getText(), Integer.parseInt(CantidadPlanta.getText())));
            System.out.println("Mostrando usuario planta");
            TABLERO.usuarios.Mostrar();
        } else {
            
            System.out.println("Error verifique que no tengas mas usuarios,sino llame al administrador del juego");
        }
        usuplantas=NombrePlanta.getText();
        jButton1.setEnabled(false);
        otroplanta.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PLANTAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PLANTAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PLANTAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PLANTAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PLANTAS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarPlantas;
    private javax.swing.JTextField CantidadPlanta;
    private javax.swing.JTextField NombrePlanta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton otroplanta;
    // End of variables declaration//GEN-END:variables

    public void limpiarUsuarios() {
        Nodo aux = TABLERO.usuarios.primero;
        while (aux != null) {
            TABLERO.usuarios.getPrimero();
            aux = aux.siguiente;
        }
    }
}
